import { CreditCard, Download, Plus, Sparkles, Users } from 'lucide-react';
import { api } from '../api.js';
import { EmptyState, PackageCard, PageIntro, StatCard } from '../components/UI.jsx';
import { money } from '../lib/constants.js';
import { downloadExcel } from '../lib/downloadExcel.js';
export default function Clients({ rows, act }) {
  const total = rows.reduce((sum, client) => sum + Number(client.credits || 0), 0);
  return <><div className="stats-grid client-stats"><StatCard label="Active brands" value={rows.filter((client) => client.status === 'active').length} note="On an active package" icon={Users} accent="icon-violet" /><StatCard label="Credits in circulation" value={total} note="Across all brand accounts" icon={Sparkles} accent="icon-amber" /><StatCard label="Open invoices" value="3" note={money(74500)} icon={CreditCard} accent="icon-green" /></div><PageIntro title="Brand accounts" detail="Manage partner packages, credits and billing." action={<button className="button button-secondary" onClick={() => downloadExcel('rsvp-dxb-clients.xlsx', ['Brand', 'Package', 'Events', 'Credits', 'Status'], rows.map((client) => [client.name, client.package, client.events, client.credits, client.status]), 'Clients')}><Download size={15} /> Export Excel</button>} /><div className="panel table-panel table-scroll"><table><thead><tr><th>BRAND</th><th>PACKAGE</th><th>EVENTS</th><th>CREDITS</th><th>ACCOUNT STATUS</th><th>QUICK ACTION</th></tr></thead><tbody>{rows.map((client) => <tr key={client.id}><td><div className="member-cell"><span className="brand-avatar brand-avatar-small">{client.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</span><div><strong>{client.name}</strong><span>Partner account</span></div></div></td><td><span className="package-pill">{client.package}</span></td><td>{client.events}</td><td><strong className={client.credits < 10 ? 'low-credits' : 'points-cell'}>{client.credits}</strong></td><td><span className={`status-tag status-${client.status === 'active' ? 'approved' : 'pending'}`}>{client.status}</span></td><td><div className="table-actions"><button className="small-action" onClick={() => act(() => api.addCredits(client.id, 10), `10 credits added to ${client.name}`)}><Plus size={13} /> 10 credits</button></div></td></tr>)}</tbody></table>{rows.length === 0 && <EmptyState title="No brand accounts" detail="Partner accounts will appear here." />}</div><PageIntro title="Packages" detail="Services offered to brand partners." /><div className="package-grid"><PackageCard name="The Guest List" price="AED 6,500" desc="Curated guest list and RSVP management." tags="Guest curation · Invitations · Check-in" /><PackageCard name="The Full Evening" price="AED 18,000" desc="End-to-end event production and hosting." tags="Styling · Catering · Photography" /><PackageCard name="The Launch at Home" price="AED 32,000" desc="Private residence launch with media and creators." tags="Press · Content · Full report" /></div></>;

}


