import { ArrowUpRight, CalendarDays, ChevronRight, CreditCard, Ellipsis, FileText, Radio, ScanLine, Sparkles, TicketCheck, Users } from 'lucide-react';
import { Attention, EmptyState, PageIntro, StatCard } from '../components/UI.jsx';
import { dateLabel } from '../lib/constants.js';
export default function Dashboard({ data, navigate }) {
  const stats = data.dashboard || {};
  const live = data.events.filter((event) => event.status === 'published');
  const pending = data.applications.filter((item) => item.status === 'pending');
  const totalCapacity = live.reduce((n, event) => n + Number(event.capacity || 0), 0);
  const totalConfirmed = live.reduce((n, event) => n + Number(event.confirmed || 0), 0);
  const fill = totalCapacity ? Math.round((totalConfirmed / totalCapacity) * 100) : 0;
  return <>
    <div className="welcome-line"><div><h2>Good morning, Tejas <span>✦</span></h2><p>Here’s what’s happening across RSVP DXB today.</p></div><div className="date-chip"><CalendarDays size={15} />{new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' })}</div></div>
    <div className="stats-grid"><StatCard label="Applications pending" value={stats.pendingApplications ?? pending.length} note="Review within 48 hours" icon={FileText} accent="icon-amber" /><StatCard label="Approved members" value={(stats.members ?? data.members.length).toLocaleString()} note="Across all tracks" icon={Users} trend="8.4%" accent="icon-violet" /><StatCard label="RSVPs this week" value={stats.weeklyRsvps ?? totalConfirmed} note="Across live events" icon={TicketCheck} trend="12.6%" accent="icon-green" /><StatCard label="Checked in tonight" value={`${stats.checkedIn ?? data.guests.filter((guest) => guest.checkedInAt).length}/${stats.expected ?? data.guests.length}`} note="Sunset Listening Session" icon={ScanLine} accent="icon-blue" /></div>
    <div className="dashboard-grid"><section className="panel queue-panel"><PageIntro title="Application queue" detail="Profiles waiting for your review" action={<button className="text-button" onClick={() => navigate('applications')}>View all <ArrowUpRight size={14} /></button>} /><div className="queue-list">{pending.slice(0, 4).map((item) => <div className="queue-row" key={item.id}><div className="avatar avatar-soft">{item.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</div><div className="queue-person"><strong>{item.name}</strong><span>{item.detail || item.email}</span></div><span className={`track-tag ${item.track === 'Private Circle' ? 'tag-red' : ''}`}>{item.track}</span><span className="muted-text queue-date">{dateLabel(item.submitted)}</span><span className="status-dot amber-dot" /></div>)}{pending.length === 0 && <EmptyState title="You’re all caught up" detail="New applications will show up here." />}</div><div className="panel-footer"><span>{pending.length} profiles need review</span><button onClick={() => navigate('applications')}>Open application queue <ChevronRight size={14} /></button></div></section>
      <section className="panel attention-panel"><PageIntro title="Needs attention" detail="A few things to keep an eye on" /><div className="attention-list"><Attention label="Events awaiting approval" value={data.events.filter((event) => event.status === 'pending').length} icon={CalendarDays} onClick={() => navigate('events')} /><Attention label="Wall posts pending" value={data.wall.filter((post) => post.status === 'pending').length} icon={Radio} onClick={() => navigate('wall')} /><Attention label="Brands low on credits" value={data.clients.filter((client) => client.credits < 10).length} icon={CreditCard} onClick={() => navigate('clients')} /><Attention label="Content submissions" value={7} icon={Sparkles} onClick={() => navigate('members')} /></div></section></div>
    <section className="panel live-events-panel"><PageIntro title="Live events" detail="Upcoming events across your programme" action={<button className="text-button" onClick={() => navigate('events')}>Manage events <ArrowUpRight size={14} /></button>} /><div className="table-scroll"><table><thead><tr><th>EVENT</th><th>BRAND</th><th>DATE</th><th>GUESTS</th><th>CAPACITY</th><th>FILL RATE</th><th /></tr></thead><tbody>{live.slice(0, 5).map((event) => { const percent = Math.min(Math.round((event.confirmed / event.capacity) * 100), 100); return <tr key={event.id}><td><div className="event-name-cell"><span className="event-thumb">{event.category?.slice(0, 1) || 'E'}</span><strong>{event.title}</strong></div></td><td>{event.brand}</td><td>{dateLabel(event.date)}</td><td>{event.confirmed}</td><td>{event.capacity}</td><td><div className="fill-cell"><span className="progress-track"><i style={{ width: `${percent}%` }} /></span><b>{percent}%</b></div></td><td><button className="icon-button row-more" onClick={() => navigate('events')} aria-label="Open event"><Ellipsis size={17} /></button></td></tr>; })}</tbody></table>{live.length === 0 && <EmptyState title="No live events yet" detail="Create an event to start building your programme." />}</div><div className="events-summary"><span><i className="green-dot" />{live.length} published events</span><span><b>{fill}%</b> average capacity filled</span></div></section>
  </>;
}

