import { useState } from 'react';
import { ArrowUpRight, Check, Plus, X } from 'lucide-react';
import { api } from '../api.js';
import { EmptyState, PageIntro } from '../components/UI.jsx';
import { TRACKS, dateLabel } from '../lib/constants.js';
export default function Events({ rows, guests, act, openModal }) {
  const [filter, setFilter] = useState('all');
  const shown = rows.filter((event) => filter === 'all' || event.status === filter);
  return <><PageIntro title="Event programme" detail="Create, review and publish experiences across Dubai." action={<div className="event-filter"><button className={filter === 'all' ? 'selected' : ''} onClick={() => setFilter('all')}>All events</button><button className={filter === 'published' ? 'selected' : ''} onClick={() => setFilter('published')}>Published</button><button className={filter === 'pending' ? 'selected' : ''} onClick={() => setFilter('pending')}>Needs review</button></div>} /><div className="panel table-panel table-scroll"><table><thead><tr><th>EVENT</th><th>BRAND</th><th>DATE & TIME</th><th>GUESTS</th><th>STATUS</th><th>AUDIENCE</th><th /></tr></thead><tbody>{shown.map((event) => <tr key={event.id}><td><div className="event-name-cell"><span className="event-thumb">{event.category?.slice(0, 1) || 'E'}</span><div><strong>{event.title}</strong><span>{event.venue}</span></div></div></td><td>{event.brand}</td><td>{dateLabel(event.date)}<span className="table-subline">{event.time}</span></td><td><strong>{event.confirmed || 0}</strong><span className="muted-text"> / {event.capacity}</span></td><td><span className={`status-tag status-${event.status}`}>{event.status}</span></td><td>{(event.tracks || []).map((name) => name === 'Private Circle' ? 'Private' : name).join(', ')}</td><td><div className="table-actions">{event.status === 'pending' ? <button className="small-action publish-action" onClick={() => act(() => api.updateEvent(event.id, 'published'), 'Event published')}>Publish</button> : <button className="small-action" onClick={() => act(() => api.updateEvent(event.id, 'closed'), 'RSVPs closed')}>Close RSVPs</button>}<button className="small-action" onClick={() => openModal({ type: 'guest-list', event })}>Guest list</button></div></td></tr>)}</tbody></table>{shown.length === 0 && <EmptyState title="No events in this view" detail="Create an event to fill your programme." />}</div></>;
}

export function EventModal({ close, act }) {
  const [form, setForm] = useState({ title: '', brand: '', venue: '', date: '', time: '', capacity: 80, category: 'Dining', tracks: ['Creators'] });
  const [busy, setBusy] = useState(false);
  const set = (key, value) => setForm((prev) => ({ ...prev, [key]: value }));
  const submit = async (status) => { if (!form.title || !form.brand || !form.date) return; setBusy(true); await act(() => api.createEvent({ ...form, status, confirmed: 0 }), status === 'published' ? 'Event created and published' : 'Event saved as draft'); setBusy(false); close(); };
  const toggle = (name) => set('tracks', form.tracks.includes(name) ? form.tracks.filter((track) => track !== name) : [...form.tracks, name]);
  return <div className="modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) close(); }}><section className="modal-card"><div className="modal-header"><div><div className="eyebrow">EVENT SETUP</div><h2>Create an event</h2></div><button className="icon-button" onClick={close}><X size={18} /></button></div><div className="modal-body"><label className="field"><span>Event title *</span><input autoFocus value={form.title} onChange={(e) => set('title', e.target.value)} placeholder="e.g. Sunset Listening Session" /></label><div className="form-grid"><label className="field"><span>Host brand *</span><input value={form.brand} onChange={(e) => set('brand', e.target.value)} placeholder="Brand name" /></label><label className="field"><span>Category</span><select value={form.category} onChange={(e) => set('category', e.target.value)}>{['Dining', 'Fashion', 'Property', 'Music', 'Art', 'Nightlife', 'Wellness', 'Travel'].map((name) => <option key={name}>{name}</option>)}</select></label><label className="field"><span>Date *</span><input type="date" value={form.date} onChange={(e) => set('date', e.target.value)} /></label><label className="field"><span>Time</span><input type="time" value={form.time} onChange={(e) => set('time', e.target.value)} /></label><label className="field"><span>Venue</span><input value={form.venue} onChange={(e) => set('venue', e.target.value)} placeholder="Venue and area" /></label><label className="field"><span>Guest capacity</span><input type="number" min="1" value={form.capacity} onChange={(e) => set('capacity', Number(e.target.value))} /></label></div><div className="field"><span>Invited tracks</span><div className="track-checks">{TRACKS.map((name) => <button key={name} className={form.tracks.includes(name) ? 'checked' : ''} onClick={() => toggle(name)} type="button">{form.tracks.includes(name) && <Check size={13} />}{name}</button>)}</div></div></div><div className="modal-footer"><button className="button button-secondary" onClick={close}>Cancel</button><button className="button button-secondary" disabled={busy || !form.title || !form.brand || !form.date} onClick={() => submit('draft')}>Save draft</button><button className="button button-primary" disabled={busy || !form.title || !form.brand || !form.date} onClick={() => submit('published')}>{busy ? 'Saving…' : 'Publish event'} <ArrowUpRight size={15} /></button></div></section></div>;
}

export function GuestModal({ event, guests, close }) {
  const rows = guests.filter((guest) => guest.eventId === event.id);
  return <div className="modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) close(); }}><section className="modal-card guest-modal"><div className="modal-header"><div><div className="eyebrow">GUEST LIST</div><h2>{event.title}</h2><p>{dateLabel(event.date)} · {event.venue}</p></div><button className="icon-button" onClick={close}><X size={18} /></button></div><div className="panel table-panel table-scroll"><table><thead><tr><th>GUEST</th><th>TRACK</th><th>PARTY SIZE</th><th>ENTRY CODE</th><th>STATUS</th></tr></thead><tbody>{rows.map((guest) => <tr key={guest.id}><td><strong>{guest.name}</strong></td><td>{guest.track}</td><td>{guest.plusOnes + 1}</td><td><code>{guest.code}</code></td><td><span className={`status-tag ${guest.checkedInAt ? 'status-approved' : 'status-pending'}`}>{guest.checkedInAt ? `Checked in ${guest.checkedInAt}` : 'Confirmed'}</span></td></tr>)}</tbody></table>{rows.length === 0 && <EmptyState title="Guest list is empty" detail="Confirmed RSVPs will appear here." />}</div><div className="modal-footer"><span className="muted-text">{rows.length} confirmed guests</span><button className="button button-secondary" onClick={close}>Done</button></div></section></div>;
}

